name: sqfentity_gen
homepage: https://github.com/qijie07/sqfentity_gen
authors:
  - Wyatt <storykym@gmail.com>
description: SqfnEntity Model Generator. SQLite ORM for Flutter lets you build and execute SQL commands easily and quickly with the help of fluent methods similar to .Net Entity Framework.

environment:
  sdk: '>=3.0.0'
  flutter: ">=3.10.0"

dependencies:
  build: 2.4.1
  source_gen: 1.5.0
  meta: 1.12.0
  analyzer: 5.13.0
  intl: 0.19.0
